### ISSUE TITLE
cocoapi modify

### ISSUE THREAD

**Issue by zhaozhen1002** [JisuiWang/CVWC2019-pose#1]
Thanks for your great work. Have you just modified cocoapi only
? I want to use it to  bird pose detection.  what should I do?
Thank you。

**Comment by wanghao14** [comment]
@zhaozhen1002 Besides modifying cocoapi, you should add a specific dataset file like **atrw.py** in ${POSE_ROOT}/lib/dataset, which is the key component you should pay attention to.
