### ISSUE TITLE
About "image_info_test.json". 

### ISSUE THREAD

**Issue by ZP-Guo** [JisuiWang/CVWC2019-pose#5]
Thank you for your sharing code @wanghao14 . I come from this issue: [https://github.com/leoxiaobin/deep-high-resolution-net.pytorch/issues/68](url). In this issue of the HRNet, we discuss how to use other datasets and you give your method that can work. I follow your code because I also want to train the HRNet with other dataset.
However a problem comes, you know, the file "image_info_test.json". Where can I get this one. I do not want to get what the file has. Just I want to know the format in it.
Finally congratulations to you for  CVWC2019 and waitting for your reply in hope.

**Comment by wanghao14** [comment]
@ZP-Guo I've forgotten a lot of details because I have done something else recently. I found a file named "image_info_test.json" in my folder and its format is in COCO format:

> "annotations": [
        {
            "area": 989324, 
            "bbox": [
                0, 
                0, 
                1246, 
                794
            ], 
            "category_id": 1, 
            "id": 2523, 
            "image_id": 2523, 
            "iscrowd": 0, 
            "keypoints": [
                0, 
                0, 
                1, 
                0, 
                0, 
                1, 
                0, 
                0, 
                1, 
                0, 
                0, 
                1, 
                0, 
                0, 
                1, 
                0, 
                0, 
                1, 
                0, 
                0, 
                1, 
                0, 
                0, 
                1, 
                0, 
                0, 
                1, 
                0, 
                0, 
                1, 
                0, 
                0, 
                0, 
                0, 
                0, 
                0, 
                0, 
                0, 
                0, 
                0, 
                0, 
                0, 
                0, 
                0, 
                0
            ], 
            "num_keypoints": 10
        }, 
        {
            "area": 162925, 
            "bbox": [
                0, 
                0, 
                475, 
                343
            ], 
……
]
"categories": [
        {
            "id": 1, 
            "keypoints": [
                "left_ear", 
                "right_ear", 
                "nose", 
                "right_shoulder", 
                "right_front_paw", 
                "left_shoulder", 
                "left_front_paw", 
                "right_hip", 
                "right_knee", 
                "right_back_paw", 
                "left_hip", 
                "left_knee", 
                "left_back_paw", 
                "tail", 
                "center"
            ], 
            "name": "tiger",
……
]
"images": [
        {
            "filename": "002523.jpg", 
            "height": 794, 
            "id": 2523, 
            "width": 1246
        }, 
        {
            "filename": "001666.jpg", 
            "height": 343, 
            "id": 1666, 
            "width": 475
        }, 
……
]

I hope this can help you.

**Comment by ZP-Guo** [comment]
@wanghao14 Thank you for your reply and your "image_info_test.json". I will go on to follow your code. Thanks a lot. 😄

**Comment by mpourkeshavarz** [comment]
@wanghao14 
I want to test the HRNet with my dataset, 
is it possible to do it without annotation file? I would be appreciated if you could give me a hint.
